# Generated by Django 4.0.2 on 2022-04-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_priority',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
