# Generated by Django 4.0.1 on 2022-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_priority',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
