# Generated by Django 4.0.2 on 2022-04-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_immigrationofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='immigration_status',
            field=models.CharField(choices=[('Immigrant', 'Immigrant'), ('Non-permanent resident', 'Non-permanent resident'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
