# Generated by Django 4.0.2 on 2022-02-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Infeected', 'Infected'), ('Recovered', 'Recovered')], default='Healthy', max_length=20),
        ),
    ]
