# Generated by Django 4.0.2 on 2022-04-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='temp_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_patients', to='accounts.doctor'),
        ),
    ]
