# Generated by Django 4.0.2 on 2022-04-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_temp_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_away',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
