# Generated by Django 4.0.1 on 2022-02-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient_address_patient_city_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
