export const GET_PERSONS = "GET_PERSONS";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON = "ADD_PERSON";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_DATA_LOADED = "USER_DATA_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_STATUS = "GET_STATUS";
export const GET_LATEST_STATUS = "GET_LATEST_STATUS";
export const GET_PATIENT_LATEST_STATUS = "GET_PATIENT_LATEST_STATUS";


