export const GET_PERSONS = "GET_PERSONS";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON = "ADD_PERSON";
export const GET_ERRORS = "GET_ERRORS";
export const DELETE_ERRORS = "DELETE_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_DATA_LOADED = "USER_DATA_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_DOCTOR = "GET_DOCTOR";

export const GET_IMMIGRANTS = "GET_IMMIGRANTS";
export const UPDATE_IMMIGRANT_PRIORITY = "UPDATE_IMMIGRANT_PRIORITY";

export const GET_ALL_STATUS = "GET_ALL_STATUS";
export const ADD_STATUS = "ADD_STATUS";
export const GET_LATEST_STATUS = "GET_LATEST_STATUS";
export const GET_PATIENT_LATEST_STATUS = "GET_PATIENT_LATEST_STATUS";

export const GET_NOTIFS = "GET_NOTIFS";
export const DELETE_NOTIF = "DELETE_NOTIF";
export const ADD_NOTIF = "ADD_NOTIF";

export const GET_ADDRESS = "GET_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const ALERT_PATIENTS = "ALERT_PATIENTS";

export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";

export const GET_AVAILABILITY = "GET_AVAILABILITY";
export const DELETE_AVAILABILITY = "DELETE_AVAILABILITY";
export const ADD_AVAILABILITY = "ADD_AVAILABILITY";


