# Generated by Django 4.0.2 on 2022-03-07 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Infected', 'Infected'), ('Recovered', 'Recovered')], default='Healthy', max_length=20)),
                ('soreThroat', models.BooleanField(default=False)),
                ('runnyNose', models.BooleanField(default=False)),
                ('sneezing', models.BooleanField(default=False)),
                ('caugh', models.BooleanField(default=False)),
                ('diffBreathing', models.BooleanField(default=False)),
                ('highTemp', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('chills', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('muscleAche', models.BooleanField(default=False)),
                ('smellOrTasteLoss', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('stomachPain', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
