# Generated by Django 4.0.1 on 2022-04-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
