# Generated by Django 4.0.1 on 2022-02-24 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='chills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='diffBreathing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='fatigue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='headache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='highTemp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='muscleAche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='runnyNose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='smellOrTasteLoss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='sneezing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='soreThroat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='stomachPain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 22, 27, 53, 973600)),
        ),
    ]
