# Generated by Django 4.0.2 on 2022-02-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_status'),
        ('companion_api', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Infected', 'Infected'), ('Recovered', 'Recovered')], default='Healthy', max_length=20),
        ),
    ]
