# Generated by Django 4.0.1 on 2022-03-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_is_priority'),
        ('companion_api', '0002_availability_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='status',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='accounts.patient'),
        ),
    ]
