# Generated by Django 4.0.1 on 2022-03-13 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companion_api', '0002_status_caugh_status_chills_status_diffbreathing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='caugh',
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
