# Generated by Django 4.0.2 on 2022-03-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companion_api', '0002_remove_address_user_address_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='accounts.patient'),
        ),
    ]
