# Generated by Django 4.0.2 on 2022-02-21 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion_api', '0003_alter_status_patient_alter_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 18, 41, 44, 855013)),
        ),
    ]
