# Generated by Django 4.0.2 on 2022-03-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion_api', '0003_alter_address_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Email', 'Email'), ('Assignment', 'Assignment'), ('Appointment', 'Appointment'), ('InfectedAlert', 'InfectedAlert')], default='Email', max_length=20),
        ),
    ]
